---

- name: "Singularuty"
  package:
    name: singularity
    state: present

- name: "OpenHPC"
   yum: 
     name: http://repos.openhpc.community/OpenHPC/2/EL_8/x86_64/ohpc-release-2-1.el8.x86_64.rpm
     state: present
     disable_gpg_check: yes

# - name: "OpenHPC"
#   apt:
#     name: http://repos.openhpc.community/OpenHPC/2/EL_8/x86_64/ohpc-release-2-1.el8.x86_64.rpm
#     state: present
#     disable_gpg_check: yes

- name: "EPEL Rep"
  package: 
    name: epel-release
    state: present

- name: "OpenHPC base"
  yum: 
    name: ohpc-base
    state: present 

